
tasks:
  - init: cargo build
    command: cargo watch -x run



#
# add needed workspace plugins for demo
#
vscode:
  extensions:
    - redhat.java
    - pomdtr.excalidraw-editor
    - zaaack.markdown-editor
